hmcts/ia-case-payments-api

build.gradle
charts/ia-case-payments-api/Chart.yaml
charts/ia-case-payments-api/values.yaml
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/Application.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/Fee.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/FeeResponse.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/FeeType.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/ExampleHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/FeeService.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/FeesRegisterApi.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/FeignErrorDecoder.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/config/FeesConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/FeeResponseTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/FeeTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/FeeTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/FeeServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/FeignErrorDecoderTest.java

[RIA-3001](https://tools.hmcts.net/jira/browse/RIA-3001)
Fees register api integration
```
[ ] Yes
[x] No
```

RIA-3001 fees register api integration

---

Jenkinsfile_CNP
build.gradle
charts/ia-case-payments-api/Chart.yaml
src/smokeTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/SmokeTest.java

Added smoke test

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/PaymentApi.java

N/A
missing headers
```
[ ] Yes
[x] No
```

missing headers

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/CreditAccountPayment.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/CreditAccountPaymentTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/PaymentServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-3374
RIA-3374_Organisation_Name
```
[ ] Yes
[X] No
```

RIA-3374 get organisation name

---

build.gradle
charts/ia-case-payments-api/Chart.yaml
charts/ia-case-payments-api/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/MakePaymentIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/SpringBootIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/WithIdamStub.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/WithRefDataStub.java
src/integrationTest/resources/organisation-response.json
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/OrganisationResponse.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/SuperUser.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/RefDataService.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/RefDataApi.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/RefDataServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-3374
RIA-3374 org name api
```
[ ] Yes
[X] No
```

RIA_3374_Org_Name_API

---

src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/SpringBootIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/WithIdamStub.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/WithRefDataStub.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/OrganisationEntityResponse.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/PaymentService.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/RefDataService.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/IdamApi.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/PaymentApi.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/RefDataApi.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/PaymentServiceTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/RefDataServiceTest.java

N/A
do not merge - testing Demo env
```
[ ] Yes
[x] No
```

Demo env settings - real integration with F&P and Ref-Data

---

src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-submit-payment-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-submit-payment-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3006-RIA-3002-EA-appeal-get-fee.json
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/AppealStartFeeIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/MakePaymentIntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/WithPaymentStub.java
src/integrationTest/resources/credit-account-payment-request_with_hearing.json
src/integrationTest/resources/credit-account-payment-request_without_hearing.json
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/Fee.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealFeePreparer.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/FeeTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealFeePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-2935
RIA-2935  Payment rework
```
[ ] Yes
[X] No
```

RIA-2935_QA_Rework (#42)

---

.travis.yml
Dockerfile
build.gradle

[RIA-3445](https://tools.hmcts.net/jira/browse/RIA-3445)
```
[x] Yes
[ ] No
```

RIA-3445 upgrading to Java11

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/security/RequestUserAccessTokenProvider.java

N/A
fix Sonar check
```
[ ] Yes
[x] No
```

fix Sonar check

---

src/functionalTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/EndpointSecurityTest.java

N/A
fix functional test
```
[ ] Yes
[x] No
```

fix functional test

---

src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-success.json
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PayAndSubmitAppealAccountPreparer.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PayAndSubmitAppealAccountPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

[RIA-3163](https://tools.hmcts.net/jira/browse/RIA-3163)
See Jira
```
[ ] Yes
[x] No
```

Ria 3163 payment after submit appeal

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealFeePreparer.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealFeePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

[RIA-3434](https://tools.hmcts.net/jira/browse/RIA-3434)
See Jira
```
[ ] Yes
[x] No
```

Ria 3434 pay offline by card pa

---

src/functionalTest/resources/scenarios/RIA-3006-RIA-3002-EA-appeal-get-fee.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-success.json
src/functionalTest/resources/templates/minimal-appeal-started.json
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/MakePaymentIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

[RIA-3583](https://tools.hmcts.net/jira/browse/RIA-3583)
Updated appealReferenceNumberHandler dispatch priority to earliest.
```
[ ] Yes
[x] No
```

RIA-3583 Updated payment request with appealReferenceNumber and legalRepReference

---

src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/AppealStartFeeIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/PaymentStatus.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealFeePreparer.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/PaymentStatusTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealFeePreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-3592
RIA-3592_payment status
```
[ ] Yes
[X] No
```

Ria 3592 payment method

---

infrastructure/main.tf
infrastructure/state.tf
infrastructure/variables.tf

RIA-3668
Azure provider upgrade
```
[ ] Yes
[x] No
```

Azure provider upgrade

---

.github/workflows/swagger.yml

[RIA-3261](https://tools.hmcts.net/jira/browse/RIA-3261)
swagger docs
```
[ ] Yes
[x] No
```

swagger docs

---

Jenkinsfile_nightly
audit.json
security.sh

[RIA-3261](https://tools.hmcts.net/jira/browse/RIA-3261)
security test
```
[ ] Yes
[x] No
```

security test

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/PreSubmitCallbackController.java

[RIA-3261](https://tools.hmcts.net/jira/browse/RIA-3261)
swagger docs update
```
[ ] Yes
[x] No
```

swagger docs update

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

N/A
improve logging + second validation for pba
```
[ ] Yes
[x] No
```

improve logging + second validation for pba

---

src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/WithRefDataStub.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/clients/RefDataApi.java

[RIA-3671](https://tools.hmcts.net/jira/browse/RIA-3671)
PRD end-point updated to send email in the header params
```
[ ] Yes
[x] No
```

RIA-3671 PRD endpoint updated to send  email as header parameter

---

build.gradle
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-submit-payment-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-submit-payment-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-success.json
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/MakePaymentIntegrationTest.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/AppealFeeDetailsHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/AppealFeeDetailsHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

Elastic search issue fixed by amending feeAmount case field to feeAmountGbp
```
[ ] Yes
[x] No
```

Amended feeAmount case field to feeAmountGbp

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/CcdScenarioRunnerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/EndpointSecurityTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/WelcomeTest.java
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/BadRequestsTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/RemissionTypeTest.java

[RIA-3705](https://tools.hmcts.net/jira/browse/RIA-3705)
```
[ ] Yes
[x] No
```

RIA-3705 Serenity tests report fix for JUnit5 runner

---

build.gradle
config/owasp/suppressions.xml

N/A
fix security vulnerabilities
```
[ ] Yes
[x] No
```

fix security vulnerabilities

---

charts/ia-case-payments-api/Chart.yaml

[RIA-3710](https://tools.hmcts.net/jira/browse/RIA-3710)
```
[ ] Yes
[x] No
```

RIA-3710 Migrate to Helm charts v2

---

Jenkinsfile_CNP
build.gradle
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/fee/FeeApiConsumerApplication.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/fee/FeeApiConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/idam/IdamApiConsumerApplication.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/idam/IdamApiConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/PaymentConsumerApplication.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/PaymentConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/refdata/RefDataConsumerApplication.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/refdata/RefDataConsumerTest.java
src/contractTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/CreditAccountPayment.java

TA-520
TA-524
TA-525
TA-526
Added in contract testing for ia-case-payments-api
```
[ ] Yes
[ X] No
```

Ta 525 consumer contract tests

---

.github/workflows/swagger.yml
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/RemissionType.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/RemissionTypeTest.java

[RIA-3218](https://tools.hmcts.net/jira/browse/RIA-3218)
Legal rep apply for a late remission
```
[ ] Yes
[x] No
```

RIA-3218 Added exceptionalCircumstancesRemission enum to RemissionType

---

build.gradle
charts/ia-case-payments-api/Chart.yaml
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-success.json

[RIA-4278](https://tools.hmcts.net/jira/browse/RIA-4278)
fix CVE and upgrade Charts
```
[ ] Yes
[x] No
```

RIA-4278 fix CVE and upgrade Charts

---

Jenkinsfile_CNP

Enable canideploy in Jenkins
```
[ ] Yes
[X ] No
```

TA-525: Enable canideploy in Jenkins

---

audit.json

N/A
fix Security scan
```
[ ] Yes
[x] No
```

fix Security scan

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java

N/A
fix NPE in case of bad request error
```
[ ] Yes
[x] No
```

fix NPE in case of bad request error

---

src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-without-hearing-success.json
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/ccd/Event.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/ccd/EventTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

[RIA-4465](https://tools.hmcts.net/jira/browse/RIA-4465) 
pay for appeal event
```
[ ] Yes
[x] No
```

RIA-4465 pay for appeal

---

src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/testutils/WithFeeStub.java
src/main/resources/application.yaml

[RIA-4496](https://tools.hmcts.net/jira/browse/RIA-4496)
new fees keywords
```
[ ] Yes
[x] No
```

RIA-4496 new fees keywords

---

Jenkinsfile_nightly

N/A
add vault loading in Jenkins
```
[ ] Yes
[x] No
```

add vault loading in Jenkins

---

build.gradle
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/fee/FeeApiConsumerTest.java

N/A
fee codes
```
[ ] Yes
[x] No
```

pact tests fee codes

---

Jenkinsfile_CNP

N/A
temporary disable pact tests
```
[ ] Yes
[x] No
```

temporary disable pact tests

---

charts/ia-case-payments-api/Chart.yaml

N/A
Charts upgrade 3.6.0
```
[ ] Yes
[x] No
```

Charts upgrade 3.6.0

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/RemissionDecision.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/RemissionDecisionTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-4909
Changes to support make a payment for remission rejected appeals
```
[ ] Yes
[X] No
```

RIA-4909: Changes to support make a payment for remission rejected appeals

---

Jenkinsfile_nightly

citizen user added to nightly jenkins

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/FeeLookupHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/FeeLookupHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

[RIA-5088](https://tools.hmcts.net/jira/browse/RIA-5088)
Change for AIP to support paymentAppeal event
```
[ ] Yes
[x] No
```

RIA-5088 Fetch fees for AIP pay later journey

---

src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/entities/CardPaymentRequest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/CardPaymentConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/GetPaymentConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/PaymentConsumerApplication.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/PbaPaymentConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/util/CardPaymentApi.java

[RIA-4845](https://tools.hmcts.net/jira/browse/RIA-4845)
Pact test for card payment
```
[ ] Yes
[x] No
```

RIA-4845 Pact test for card payment

---

src/main/resources/application.yaml

SOC-301121 Updated hard coded system password

---

src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/CardPaymentConsumerTest.java
src/contractTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/consumer/payment/GetPaymentConsumerTest.java
src/functionalTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/UpdatePaymentStatusTest.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/FeeDto.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/PaymentDto.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/PaymentDtoTest.java

RIA-4797 Payment and Fee dto updated

---

charts/ia-case-payments-api/Chart.yaml

https://tools.hmcts.net/jira/browse/RIA-5503
```
[ ] Yes
[x] No
```

RIA-5503: Upgrade base helm charts to latest

---

charts/ia-case-payments-api/Chart.yaml

Version bump

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/ServiceRequestService.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/ServiceRequestServiceTest.java

[RIA-5721](https://tools.hmcts.net/jira/browse/RIA-5721)
- The "Party" property shown in a Service Request is supposed to be "Firstname Lastname"
```
[ ] Yes
[x] No
```

RIA-5721 Make "Party" be "Firstname Lastname"

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/ServiceRequestUpdateController.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/ServiceRequestUpdateControllerTest.java

[RIA-5721](https://tools.hmcts.net/jira/browse/RIA-5721)
- Data send to update the payments status in the case data should be the data nested within the payment
```
[ ] Yes
[x] No
```

RIA-5721 Amend data sent when updating payment status

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/ServiceRequestUpdateDto.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/ServiceRequestUpdateController.java
src/main/resources/application.yaml

[RIA-5722](https://tools.hmcts.net/jira/browse/RIA-5722)
- logs and nonNull constrictions added
```
[ ] Yes
[x] No
```

RIA-5722 Whitelist payment_app, add nonNull contraints, and logging

---

src/main/resources/application.yaml

[RIA-5813](https://tools.hmcts.net/jira/browse/RIA-5813)
- Edited the callback-url in application-yaml
```
[ ] Yes
[x] No
```

RIA-5813 fee n pay local setup

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AppealType.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AppealTypeTest.java

- [RIA-5587](https://tools.hmcts.net/jira/browse/RIA-5587)
- [RIA-5895](https://tools.hmcts.net/jira/browse/RIA-5895)
- [RIA-5586](https://tools.hmcts.net/jira/browse/RIA-5586)
- [RIA-6163](https://tools.hmcts.net/jira/browse/RIA-6163)
- Added EU ("EU Settlement Scheme" to AppealType enum)
```
[ ] Yes
[x] No
```

RIA-5587 Add EU to appealType

---

build.gradle
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

[RIA-6169](https://tools.hmcts.net/jira/browse/RIA-6169)
- Added RECORD_REMISSION_DECISION to list of events to handle by PaymentAppealPreparer
```
[ ] Yes
[x] No
```

RIA-6169 service requests and remissions

---

build.gradle
config/owasp/suppressions.xml

[RIA-5844](https://tools.hmcts.net/jira/browse/RIA-5844)
CVE-2020-5408
CVE-2022-22976
CVE-2022-22978
```
[ ] Yes
[x] No
```

Ria 5679 address vulnerabilities m

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java

[RIA-6229](https://tools.hmcts.net/jira/browse/RIA-6229) and others
- Add remissions condition to if statement
```
[ ] Yes
[x] No
```

RIA-6229 Add hasNoRemission boolean

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/postsubmit/SubmitAppealCreateServiceRequestHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/postsubmit/SubmitAppealCreateServiceRequestHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

[RIA-6172](https://tools.hmcts.net/jira/browse/RIA-6172)
Integration for EU cases with the new Ways2Pay payment process. EU cases are supposed to follow the same behavior of HU and EA cases.
- Added EU to all payment related conditions that were relevant for HU and EA cases
```
[ ] Yes
[x] No
```

Ria 6172 integrate new ways2 pay with eu

---

src/functionalTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/UpdatePaymentStatusTest.java

Updates to fix master build failure
Updates to fix master build failure
Updates to fix master build failure
```
[ ] Yes
[X ] No
```

Updates to fix master build failures

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AppealType.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AppealTypeTest.java

https://tools.hmcts.net/jira/browse/RIA-6437
Created long running branch
```
[ ] Yes
[X] No
```

Ria 6437 submit age assessment appeal

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

- Treat Ada appeals as RP/DC (no payment)

RIA-6563 : Not change payment status for Ada Appeals

---

Jenkinsfile_CNP
build.gradle
charts/ia-case-payments-api/Chart.yaml
config/owasp/suppressions.xml

To upgrade java chart version
To upgrade java chart version
```
[ ] Yes
[ X] No
```

To upgrade java chart version

---

charts/ia-case-payments-api/Chart.yaml

To revise chart version
To revise chart version
```
[ ] Yes
[ X] No
```

To revise chart version

---

charts/ia-case-payments-api/Chart.yaml
config/owasp/suppressions.xml

Updates to suppress CVEs on NABA branch
Updates to suppress CVEs on NABA branch
```
[ ] Yes
[ X] No
```

Updates to suppress CVEs on NABA branch

---

Dockerfile
charts/ia-case-payments-api/Chart.yaml
config/owasp/suppressions.xml
infrastructure/state.tf
infrastructure/variables.tf

Rebase changes from master to NABA branch
```
[ ] Yes
[x] No
```

Rebase from Master

---

src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

start new build of same branch with no changes

---

config/owasp/suppressions.xml

Empty line commit

---

config/owasp/suppressions.xml

and suppress vulnerability.
```
[ ] Yes
[x] No
```

Rebuild naba branch

---

build.gradle
config/owasp/suppressions.xml

RIA-7724
Upgrade libraries to solve vulnerabilities
```
[ ] Yes
[x] No
```

RIA-7724 Solve suppressions

---

config/owasp/suppressions.xml

RIA-7585 Empty line commit

---

config/owasp/suppressions.xml

RIA-7280 Empty commit

---

build.gradle
config/owasp/suppressions.xml

Merged Master changes to Naba Payments
```
[ ] Yes
[x] No
```

RIA-TASK - Merged Master changes to NABA Payments

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RIA-5679
Updated suppression for cve-2023-35116
```
[ ] Yes
[X] No
```

RIA-5679 Updated suppressions

---

config/owasp/suppressions.xml

Building pipeline to spark image creation

RIA-8888 rebuilding pipeline to allow for image issues to be addressed

---

config/owasp/suppressions.xml

Updating for pipeline
```
[ ] Yes
[ x ] No
```

RIA-7814 Update suppressions.xml

---

config/owasp/suppressions.xml

Rebuilding image
```
[ ] Yes
[ x ] No
```

RIA-7454 Update suppressions.xml

---

.github/renovate.json

https://tools.hmcts.net/jira/browse/DIAC-2
Updating renovate config options
```
[ ] Yes
[x] No
```

DIAC-2 updating renovate config options

---

charts/ia-case-payments-api/Chart.yaml

upgrade chart version
```
[ ] Yes
[ x ] No
```

RIA-8888 upgrade chart version

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java

RIA-7447 EJP appeals should not go through payment process

---

src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/FeeServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-7734
Tiny change for NABA rebuild
```
[ ] Yes
[ ] No
```

RIA-7734 fix_image

---

build.gradle

RIA-TASK - Fixed dependency issue relating to logging

RIA-TASK - Fixed dependency issue relating to logging

---

.github/renovate.json
build.gradle
charts/ia-case-payments-api/Chart.yaml

https://tools.hmcts.net/jira/browse/DIAC-2
Adding some exclusions to renovate json for pitest and pact
```
[ ] Yes
[ ] No
```

DIAC-002 Updating renovate json to exclude two plugins

---

build.gradle

DIAC-002 based fix

---

src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java

rebuild the pipelines
```
[ ] Yes
[ ] No
```

RIA-8045 rebuild  payments

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DIAC-173
```
[ ] Yes
[ ] No
```

DIAC-173 dependency fixes

---

config/owasp/suppressions.xml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/CreditAccountPaymentTest.java

Restart the pipelines
```
[ ] Yes
[ ] No
```

RIA-2023 rebuild_pipelines

---

build.gradle

DIAC-184 build fix 18-12-23

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/DIAC-103
```
[ ] Yes
[ ] No
```

DIAC-103 connecting and turning on fortify

---

build.gradle
charts/ia-case-payments-api/values.preview.template.yaml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/ServiceRequestRetryTest.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/Application.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/ServiceRequestService.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/ServiceRequestServiceTest.java

DIAC-154 adding retry to service request

---

src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/controllers/PreSubmitCallbackControllerTest.java

https://tools.hmcts.net/jira/browse/RIA-7833
- To rebuild pipeline

RIA-7833 Commit to rebuild pipeline

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/HelpWithFeesOption.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/RemissionOption.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java

https://tools.hmcts.net/jira/browse/RIA-8761
Added No_remission condition for Aip journey to PaymentAppealPreparer.
```
[ ] Yes
[ ] No
```

RIA-8761 add_no_remission_option

---

config/owasp/suppressions.xml

retrigger NABA image build
```
[ ] Yes
[ x ] No
```

RIA-8888 updated suppressions.xml

---

Jenkinsfile_CNP
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AppealType.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/ccd/State.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AppealTypeTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/ccd/StateTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/payment/CreditAccountPaymentTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/service/FeeServiceTest.java

https://tools.hmcts.net/jira/browse/RIA-8860
RIA-8860 Merge with master

RIA-8860 Merge with master

---

charts/ia-case-payments-api/Chart.yaml

https://tools.hmcts.net/jira/browse/DIAC-401

DIAC-401 bump chart version

---

charts/ia-case-payments-api/Chart.yaml

Bump charts version
Some of the template versions/names were straightened out in the 5.2.1 release. We're hoping this will help fix https://tools.hmcts.net/jira/browse/DIAC-401

DIAC-401 Update chart version

---

charts/ia-case-payments-api/Chart.yaml
charts/ia-case-payments-api/values.yaml
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/CcdDataService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/CcdDataServiceTest.java

https://tools.hmcts.net/jira/browse/DIAC-417
Add logs in update payment status controller
```
[ ] Yes
[x] No
```

DIAC-510 Add logs in update payment status controller

---

build.gradle
charts/ia-case-payments-api/Chart.yaml
charts/ia-case-payments-api/values.preview.template.yaml
charts/ia-case-payments-api/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DIAC-540
remove deprecated config and add configtree config
```
[ ] Yes
[x] No
```

DIAC-540 - remove deprecated config and add configtree config

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/infrastructure/service/CcdDataService.java

DIAC-000 - remove debugging

---

build.gradle
charts/ia-case-payments-api/Chart.yaml
charts/ia-case-payments-api/values.preview.template.yaml
charts/ia-case-payments-api/values.yaml
src/main/resources/application.yaml

RIA-TASK - Rebase master 
```
[ ] Yes
[ ] No
```

RIA-TASK - Rebase master ia-case-payments

---

build.gradle

Get participantVersion from GIT_COMMIT env var
Similar to https://github.com/hmcts/ia-hearings-api/pull/452
```
[ ] Yes
[ x ] No
```

RIA-TASK Get participantVersion from GIT_COMMIT env var

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandler.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparer.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandlerTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/PaymentAppealPreparerTest.java

https://tools.hmcts.net/jira/browse/RIA-9552
Enable service request for AIP journey
```
[ ] Yes
[ x ] No
```

RIA-9552 Enable service request for AIP journey

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/FeeTribunalAction.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/FeeTribunalActionTest.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9554
Allow additional payment service request
```
[ ] Yes
[ x ] No
```

RIA-9554 Allow additional payment service request

---

src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/AsylumCaseDefinition.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/entities/fee/Fee.java
src/main/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandler.java
src/test/java/uk/gov/hmcts/reform/iacasepaymentsapi/domain/handlers/presubmit/CreateServiceRequestHandlerTest.java

https://tools.hmcts.net/jira/browse/RIA-9558
MFA additional amount for service request
```
[ ] Yes
[ x ] No
```

RIA-9558 MFA additional amount for service request

---

build.gradle

https://tools.hmcts.net/jira/browse/DIAC-857
GIT_COMMIT null in Local Build - if System.env.GIT_COMMIT is null (as it is in local) use getCheckedOutGitCommitHash()
```
[ ] Yes
[x] No
```

DIAC-857 GIT_COMMIT null in Local Build 

---

src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-submit-payment-hearing.json
src/functionalTest/resources/scenarios/RIA-2935-EA-appeal-submit-payment-without-hearing.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-account-on-hold.json
src/functionalTest/resources/scenarios/RIA-3082-EA-pay-now-and-submit-without-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-3163-PA-make-a-payment-without-hearing-success.json
src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-with-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-with-hearing-success.json
src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-without-hearing-account-deleted.json
src/functionalTest/resources/scenarios/RIA-4465-pay-for-appeal-without-hearing-success.json
src/functionalTest/resources/scenarios/RIA-4801-hearing-fee-lookup-for-aip-journey-edit-appeal.json
src/functionalTest/resources/scenarios/RIA-4801-hearing-fee-lookup-for-aip-journey-start-appeal.json
src/functionalTest/resources/scenarios/RIA-4801-without-hearing-fee-lookup-for-aip-journey.json

DIAC-688 - update feeversion from 2 to 3

---

build.gradle

DIAC-000 Dependency check fix
